### ISSUE TITLE
欢迎大家来了解并使用 Fantastic-admin

### ISSUE THREAD

**Issue by hooray** [hooray/fantastic-admin#1]
<p align="center">
    <img src="https://hooray.gitee.io/fantastic-admin/logo.png" width="200" height="200" />
</p>

<h1 align="center">Fantastic-admin</h1>

## 这是什么

一款开箱即用的 Vue 中后台管理系统模版

## 特点

- 丰富的布局模式，覆盖市面上各种中后台布局
- 提供主题配置文件，轻松实现个性化定制
- 根据路由配置自动生成导航栏
- 支持全方位权限验证

## 演示

[基础版](https://hooray.gitee.io/fantastic-admin/basic)（免费，可商用）

[专业版](https://hooray.gitee.io/fantastic-admin/pro)（付费，购买方式请查看演示地址首页说明）

## 文档

[点击查看](https://hooray.gitee.io/fantastic-admin)

## 预览

> 预览截图为专业版

![](https://hooray.gitee.io/fantastic-admin/preview1.png)
![](https://hooray.gitee.io/fantastic-admin/preview2.png)
![](https://hooray.gitee.io/fantastic-admin/preview3.png)
![](https://hooray.gitee.io/fantastic-admin/preview4.png)

## 支持

给个小 ❤️ 吧~

[![star](https://gitee.com/hooray/fantastic-admin/badge/star.svg?theme=dark)](https://gitee.com/hooray/fantastic-admin/stargazers)

**Comment by hooray** [comment]
@MooNkirA @aroundone @allen-lhj @chuzhixin @hailinmo @Pilchard3 @2275596407 @WenChaoGit @Mooshowl @yuluolingze @SU79840 @H-copy @tuuzed @Harhao @laoluo791 @zhaowei210 @Oda-T @Faqahat @cnli @gitHub-ljrong @HaoYangkun @Core130 @zhangpanfei @leehave @lzread @hyhyy @zag-Coding @xksgs @bulangnisi @xushankun

**Comment by hooray** [comment]
@liuxilei @Yuushigure @plong009 @liuyuanlin0111 @hustlyt @jamesyu89 @LionsArmstrong @flashjay @lrt6186021 @Sicau-HsuYang @dengzhaofun @hdtopku @qinkaiabc @also1024 @shanei5107 @wenwenwen1206 @huanggengzhong @laienshun @Columbine21 @ShadowRim @niceskylei @jiji262 @sleepyGirl0917 @Jessie-Liu003 @cyxiaotian @caidaorui @Zmc-93 @LeoNooob @Darren-chenchen @lichenzhuo

**Comment by hooray** [comment]
@lirui9825 @youyoudong @beldon @118110afa @samulle @Woomay @bmy5585 @lookenghua @hc-tec @skryun @Sun11l @WindSearcher @free-heart @gary0416 @MrMeno @hongjojjay @CoderAFI @909559792 @wohenguaii @Zarek-Xeons @wedison1120 @JAY666666 @czren12 @oceanking @QuTnice @domsgit @zepc007 @mickeywang1998 @tinyhots @Samdyddd

**Comment by hooray** [comment]
@wcx14311 @pikaqiunet @V-Reality @dionglv @cagev @rmlzy @QianJinGuo @edisonzzzzzhang @Desperado2018 @zhaoxm469 @whyxr @Rblog @CodeMonkeyLuffy @Layczm @xyzdh @wanjinzhong @1317258331 @betazk @DaiYz @zvictorino @HunterLomo @kangsgo @liangchencl @FunamiYui @xinlee0113 @artdong @2297204105 @jacksuc @freechen @maoqiq

**Comment by hooray** [comment]
@bradypodest @cgrddv @Charleyi @sky8652 @Kidy4088 @marswang @lngwu11 @lokiyun @ZhiXiao-Lin @libo2452 @RaymonYao @NAMEs @XingXiaoWu @PakTo @hexiaoxiong @arsqu @zzjA @shanghaiese @niceue @LastStartDust @thelostword @jetwong88 @vrrobot @qingyuun @DaYu525 @louieaa @Ai12580 @WangYuang123 @Jay-715 @franklen

**Comment by hooray** [comment]
@zequan-wu @1988chg @houxianzhou @itwangchen @imsupersb @icxldd @zhaojh329 @doun @sfyr111 @huobazi @zsptsf @pymilk @whapply @songlipeng2003 @zy12121026 @leonht @kingcourage @Assassin-King @liancheng-zcy @53356454 @chenchengfa93 @colingogogo @shenJerry @ruiyeclub @xtayga @KaGen1999 @zxiansheng @shenboren @jinghh @hu382337381 @buzai @pangchunxi521 @zhongnan1990 @cxyxiaoyuyu @sun199412 @successgo @Deangle @cnphpbb @logan70 @AriesZzzz @Tilang @yu18264881581 @snice @shone5499 @boyv-liu @yzqnf @shashakeaiduo @Ijustoneway @gujintao1900 @leochinacn @mosegudu @a982246809 @prtens @hexf00 @kangqiangzj @izzh365 @sunny-mood @gmihan @joel785454405 @17865135532 @l455202325 @xu98 @anxuanzi @vajacn @LALH @fubixingwzy @cheng87126 @vacjaliu @rangowuchen @C-yz0322 @rourkesu2015 @shmilylty @sanxin @Connor-Lu @as26220635 @eshun @superau @wywq @felixmayeya @atticus91 @sptrs @houchuanguo @islittlezhou @240011814 @fangnan5233 @FeatherBlack @alexzarkk @lmmonster @TheCat01029 @WNweinan091251 @zhangkesheng @popdzytz @Shen-Yu @Koch0130 @sun519 @suiwuyi @qianhuaipeng @springcloud-zym @sisihuisi @HexFF @b1ueb0y @yueqiqi @xiangfengsu @fupinglee @FormalistBlue @chengjunjian @keycz @mydvdf @lordtang @RefinedMe @u10k @mhahaha @onedou @whiter001 @mvpssr @XiaoGuaiShow @weikaidai @Jelly36 @Lings1024 @github-longdada @Frunck8206 @bosen365 @yulanubs @wtry @Niexiawei @snowords @jiuzhuaxiong @sigongli @qingshangi @longletian @ALICEOFALICE @superdragon @Aifadian @shandudu @sunjian2009 @nqykl @toobigdata @Arther1228 @Teviz @Wall-ee @XeonSid @diyigemt @thegumza @fosin @tercel2018 @Ronaldoshuang @netsail @coolbull @jianjin712 @Latezly

**Comment by hooray** [comment]
@mosegudu @a982246809 @prtens @hexf00 @kangqiangzj @izzh365 @sunny-mood @gmihan @joel785454405 @17865135532 @l455202325 @xu98 @anxuanzi @vajacn @LALH @fubixingwzy @cheng87126 @vacjaliu @rangowuchen @C-yz0322 @rourkesu2015 @shmilylty @sanxin @Connor-Lu @as26220635 @eshun @superau @wywq @felixmayeya @atticus91 @sptrs @houchuanguo @islittlezhou @240011814 @fangnan5233 @FeatherBlack @alexzarkk @lmmonster @TheCat01029 @WNweinan091251 @zhangkesheng @popdzytz @Shen-Yu @Koch0130 @sun519 @suiwuyi @qianhuaipeng @springcloud-zym @sisihuisi @HexFF @b1ueb0y @yueqiqi @xiangfengsu @fupinglee @FormalistBlue @chengjunjian @keycz @mydvdf @lordtang @RefinedMe @u10k @mhahaha @onedou @whiter001 @mvpssr @XiaoGuaiShow @weikaidai @Jelly36 @Lings1024 @github-longdada @Frunck8206 @bosen365 @yulanubs @wtry @Niexiawei @snowords @jiuzhuaxiong @sigongli @qingshangi @longletian @ALICEOFALICE @superdragon @Aifadian @shandudu @sunjian2009 @nqykl @toobigdata @Arther1228 @Teviz @Wall-ee @XeonSid @diyigemt @thegumza @fosin @tercel2018 @Ronaldoshuang @netsail @coolbull @jianjin712 @Latezly

**Comment by hooray** [comment]
@b1ueb0y @yueqiqi @xiangfengsu @fupinglee @FormalistBlue @chengjunjian @keycz @mydvdf @lordtang @RefinedMe @u10k @mhahaha @onedou @whiter001 @mvpssr @XiaoGuaiShow @weikaidai @Jelly36 @Lings1024 @github-longdada @Frunck8206 @bosen365 @yulanubs @wtry @Niexiawei @snowords @jiuzhuaxiong @sigongli @qingshangi @longletian @ALICEOFALICE @superdragon @Aifadian @shandudu @sunjian2009 @nqykl @toobigdata @Arther1228 @Teviz @Wall-ee @XeonSid @diyigemt @thegumza @fosin @tercel2018 @Ronaldoshuang @netsail @coolbull @jianjin712 @Latezly

**Comment by bulangnisi** [comment]
what are you doing ?????

**Comment by beldon** [comment]
what are you 弄啥

**Comment by DaiYz** [comment]
what are you 弄啥嘞

**Comment by popdzytz** [comment]
挺流畅的 建议加个tab选项

**Comment by anxuanzi** [comment]
建议收费便宜点

**Comment by mosegudu** [comment]
发垃圾邮件骚扰我，牛批

**Comment by 2275596407** [comment]
你们邮件回复能单发吗别@所有人，我还以为邮箱让攻击了呢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xuanzi An"<notifications@github.com&gt;; 
发送时间: 2020年10月20日(星期二) 上午9:19
收件人: "hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;; 
抄送: "a&apos;ゞゞwu丨失了分寸╮  "<2275596407@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1)





 
建议收费便宜点

**Comment by anxuanzi** [comment]
> 你们邮件回复能单发吗别@所有人，我还以为邮箱让攻击了呢！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanzi An"<notifications@github.com&gt;; 发送时间: 2020年10月20日(星期二) 上午9:19 收件人: "hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;; 抄送: "a&apos;ゞゞwu丨失了分寸╮ "<2275596407@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1) 建议收费便宜点 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Gayhub默认的啊

**Comment by sun199412** [comment]
什么东西啊，天天发




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hooray/fantastic-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 上午9:27
收件人:&nbsp;"hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;;
抄送:&nbsp;"null"<1061508999@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1)





 你们邮件回复能单发吗别@所有人，我还以为邮箱让攻击了呢！！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Xuanzi An"<notifications@github.com&amp;gt;;  
 发送时间: 2020年10月20日(星期二) 上午9:19 
 收件人: "hooray/fantastic-admin"<fantastic-admin@noreply.github.com&amp;gt;;  
 抄送: "a&amp;apos;ゞゞwu丨失了分寸╮  "<2275596407@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1) 
 
 
 
 
 
   
 建议收费便宜点

**Comment by Oda-T** [comment]
蛆

**Comment by prtens** [comment]
噢噢噢噢噢噢噢噢噢噢噢噢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hooray/fantastic-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 凌晨0:30
收件人:&nbsp;"hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;;
抄送:&nbsp;"月下的誓言"<1017098134@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1)





 
@mosegudu @a982246809 @prtens @hexf00 @kangqiangzj @izzh365 @sunny-mood @gmihan @joel785454405 @17865135532 @l455202325 @xu98 @anxuanzi @vajacn @LALH @fubixingwzy @cheng87126 @vacjaliu @rangowuchen @C-yz0322 @rourkesu2015 @shmilylty @sanxin @Connor-Lu @as26220635 @eshun @superau @wywq @felixmayeya @atticus91 @sptrs @houchuanguo @islittlezhou @240011814 @fangnan5233 @FeatherBlack @alexzarkk @lmmonster @TheCat01029 @WNweinan091251 @zhangkesheng @popdzytz @Shen-Yu @Koch0130 @sun519 @suiwuyi @qianhuaipeng @springcloud-zym @sisihuisi @HexFF

**Comment by hooray** [comment]
此 issue 为推广性质，也是关注到各位同行近期或以前有关注过中后台框架，所以才会被 at 到，但考虑不周，未考虑到开启邮箱提醒的用户，故关闭此 issue，避免大家反复收到通知提醒。

**Comment by sfyr111** [comment]
爬

**Comment by sfyr111** [comment]
爬

**Comment by longletian** [comment]
> 噢噢噢噢噢噢噢噢噢噢噢噢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hooray/fantastic-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月20日(星期二) 凌晨0:30 收件人:&nbsp;"hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;; 抄送:&nbsp;"月下的誓言"<1017098134@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1) @mosegudu @a982246809 @prtens @hexf00 @kangqiangzj @izzh365 @sunny-mood @gmihan @joel785454405 @17865135532 @l455202325 @xu98 @anxuanzi @vajacn @LALH @fubixingwzy @cheng87126 @vacjaliu @rangowuchen @C-yz0322 @rourkesu2015 @shmilylty @sanxin @Connor-Lu @as26220635 @eshun @superau @wywq @felixmayeya @atticus91 @sptrs @houchuanguo @islittlezhou @240011814 @fangnan5233 @FeatherBlack @alexzarkk @lmmonster @TheCat01029 @WNweinan091251 @zhangkesheng @popdzytz @Shen-Yu @Koch0130 @sun519 @suiwuyi @qianhuaipeng @springcloud-zym @sisihuisi @HexFF — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你是真的牛皮

**Comment by mydvdf** [comment]
不要在回复邮件了！谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "longletian"<notifications@github.com&gt;; 
发送时间: 2020年10月20日(星期二) 下午5:25
收件人: "hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;; 
抄送: "Dark angel "<296815321@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1)





  
噢噢噢噢噢噢噢噢噢噢噢噢
 …
 ------------------ 原始邮件 ------------------ 发件人: "hooray/fantastic-admin" <notifications@github.com&gt;; 发送时间: 2020年10月20日(星期二) 凌晨0:30 收件人: "hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;; 抄送: "月下的誓言"<1017098134@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题: Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1) @mosegudu @a982246809 @prtens @hexf00 @kangqiangzj @izzh365 @sunny-mood @gmihan @joel785454405 @17865135532 @l455202325 @xu98 @anxuanzi @vajacn @LALH @fubixingwzy @cheng87126 @vacjaliu @rangowuchen @C-yz0322 @rourkesu2015 @shmilylty @sanxin @Connor-Lu @as26220635 @eshun @superau @wywq @felixmayeya @atticus91 @sptrs @houchuanguo @islittlezhou @240011814 @fangnan5233 @FeatherBlack @alexzarkk @lmmonster @TheCat01029 @WNweinan091251 @zhangkesheng @popdzytz @Shen-Yu @Koch0130 @sun519 @suiwuyi @qianhuaipeng @springcloud-zym @sisihuisi @HexFF — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你是真的牛皮
 
&mdash;

**Comment by Assassin-King** [comment]
性感荷官，在线发牌~兄弟们，准备相位猛冲！！！

**Comment by rourkesu2015** [comment]
性感荷官，在线发牌~兄弟们，准备相位猛冲！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hooray/fantastic-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月20日(星期二) 下午5:28
收件人:&nbsp;"hooray/fantastic-admin"<fantastic-admin@noreply.github.com&gt;;
抄送:&nbsp;"翡翠白玉汤"<572525999@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hooray/fantastic-admin] 欢迎大家来了解并使用 Fantastic-admin (#1)





 
性感荷官，在线发牌~兄弟们，准备相位猛冲！！！
