### ISSUE TITLE
大佬，项目app.vue文件改动会报错

### ISSUE THREAD

**Issue by zhangyao1990** [hooray/fantastic-admin#14]
大佬，项目app.vue文件改动会报错，刷新就好了，能修复吗？
复现流程：开发环境
1.项目启动。
2.修改App.vue文件，比如说加个console.log('aa')也行。
3.保存
浏览器就会报错
报错信息：runtime-core.esm-bundler.js:571 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by hooray** [comment]
已修复
