### ISSUE TITLE
Search组件在页面路由过多时会存在卡顿

### ISSUE THREAD

**Issue by yeahhhz** [hooray/fantastic-admin#2]
Search组件利用opacity和visibility的切换显示是挺巧妙的。
不过当页面路由过多时会存在明显卡顿。
原因我认为是可能是子元素全部都继承opacity属性，导致内存问题。

**Comment by hooray** [comment]
我个人测试发现问题主要在 `backdrop-filter: blur(10px);` 样式上，你可以尝试去掉该样式再测试下卡顿情况是否有好转

**Comment by yeahhhz** [comment]
是的，确实是由`backdrop-filter`造成的。
