### ISSUE TITLE
动态路由组件复用问题

### ISSUE THREAD

**Issue by zhuzhuboy** [hooray/fantastic-admin#3]
我在路由中设置了动态路由，依照vue文档说明，动态路由组件会复用，组件内的生命周期不会重复执行，当我开发的时候，发现在fantastic中设置了动态路由后，组件内的生命周期函数会照常执行。这是为什么呢？

**Comment by hooray** [comment]
麻烦提供具体演示代码配合说明该问题

**Comment by geng130127** [comment]
> 麻烦提供具体演示代码配合说明该问题

没有TS版本吗、？
