### ISSUE TITLE
运行pnpm build 出现报错

### ISSUE THREAD

**Issue by duranshi** [hooray/fantastic-admin#4]
![4471B0~1](https://user-images.githubusercontent.com/88920907/133407094-006b68d5-a5ed-47a0-a409-e5588f96e931.PNG)

并不是一直会报 偶尔打包出现这个问题

**Comment by duranshi** [comment]
能不能看看，这个问题目前没发现哪里有问题，每次运行pnpm build都会这样 谢谢

**Comment by hooray** [comment]
手动删除下 dist 目录后再重新打包，看报错应该是 dist 目录下文件被占用，导致无法删除

**Comment by duranshi** [comment]
搞定了

**Comment by duranshi** [comment]
eval函数在哪里用到的  还有v::deep源码里也搜不到

**Comment by hooray** [comment]
eval 应该是 vite 构建工具里内置的，会先删除原始打包目录，然后在重新生成。
项目里没有使用到 ::v-deep ，已有最新语法 :deep() 代替
